"""教育部专业目录采集器。

数据来源：
1. 教育部《普通高等学校本科专业目录（2024年版）》
2. 教育部《职业教育专业目录（2021年版）》
3. 内建完整专业目录数据（含本科全部12个学科门类、93个专业类、816种专业）

数据结构层级：
  学科门类（category）→ 专业类 → 具体专业
  例如：工学 → 计算机类 → 计算机科学与技术
"""

from __future__ import annotations

import logging
from typing import Optional

from zhinan.collector import BaseCollector

logger = logging.getLogger(__name__)

# ==============================================================================
# 教育部《普通高等学校本科专业目录（2024年版）》
# 12大学科门类，93个专业类，816种专业
# 数据格式：{"standard_code": "代码", "name": "专业名称", "category": "学科门类", "degree_type": "授予学位"}
# ==============================================================================

MAJORS_DATA = [
    # ==================== 01 哲学 ====================
    {"standard_code": "010101", "name": "哲学", "category": "哲学", "degree_type": "哲学"},
    {"standard_code": "010102", "name": "逻辑学", "category": "哲学", "degree_type": "哲学"},
    {"standard_code": "010103", "name": "宗教学", "category": "哲学", "degree_type": "哲学"},
    {"standard_code": "010104", "name": "伦理学", "category": "哲学", "degree_type": "哲学"},

    # ==================== 02 经济学 ====================
    {"standard_code": "020101", "name": "经济学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020102", "name": "经济统计学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020103", "name": "国民经济管理", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020104", "name": "资源与环境经济学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020105", "name": "商务经济学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020106", "name": "能源经济", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020107", "name": "劳动经济学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020108", "name": "数字经济", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020201", "name": "财政学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020202", "name": "税收学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020203", "name": "国际税收", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020301", "name": "金融学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020302", "name": "金融工程", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020303", "name": "保险学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020304", "name": "投资学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020305", "name": "金融数学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020306", "name": "信用管理", "category": "经济学", "degree_type": "管理学"},
    {"standard_code": "020307", "name": "经济与金融", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020308", "name": "精算学", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020309", "name": "互联网金融", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020310", "name": "金融科技", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020311", "name": "金融审计", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020401", "name": "国际经济与贸易", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020402", "name": "贸易经济", "category": "经济学", "degree_type": "经济学"},
    {"standard_code": "020403", "name": "国际经济发展合作", "category": "经济学", "degree_type": "经济学"},

    # ==================== 03 法学 ====================
    {"standard_code": "030101", "name": "法学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030102", "name": "知识产权", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030103", "name": "监狱学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030104", "name": "信用风险管理与法律防控", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030105", "name": "国际经贸规则", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030106", "name": "司法警察学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030107", "name": "社区矫正", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030108", "name": "纪检监察", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030109", "name": "国家安全学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030201", "name": "政治学与行政学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030202", "name": "国际政治", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030203", "name": "外交学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030204", "name": "国际事务与国际关系", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030205", "name": "政治学、经济学与哲学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030206", "name": "国际组织与全球治理", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030301", "name": "社会学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030302", "name": "社会工作", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030303", "name": "人类学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030304", "name": "女性学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030305", "name": "家政学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030306", "name": "老年学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030401", "name": "民族学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030501", "name": "科学社会主义", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030502", "name": "中国共产党历史", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030503", "name": "思想政治教育", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030504", "name": "马克思主义理论", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030601", "name": "公安学类", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030601", "name": "治安学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030602", "name": "侦查学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030603", "name": "边防管理", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030604", "name": "禁毒学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030605", "name": "警犬技术", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030606", "name": "经济犯罪侦查", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030607", "name": "边防指挥", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030608", "name": "消防指挥", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030609", "name": "警卫学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030610", "name": "公安情报学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030611", "name": "犯罪学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030612", "name": "公安管理学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030613", "name": "涉外警务", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030614", "name": "国内安全保卫", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030615", "name": "警务指挥与战术", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030616", "name": "技术侦查学", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030617", "name": "海警执法", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030618", "name": "网络安全与执法", "category": "法学", "degree_type": "法学"},
    {"standard_code": "030619", "name": "数据警务技术", "category": "法学", "degree_type": "工学"},

    # ==================== 04 教育学 ====================
    {"standard_code": "040101", "name": "教育学", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040102", "name": "科学教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040103", "name": "人文教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040104", "name": "教育技术学", "category": "教育学", "degree_type": "工学或教育学"},
    {"standard_code": "040105", "name": "艺术教育", "category": "教育学", "degree_type": "艺术学"},
    {"standard_code": "040106", "name": "学前教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040107", "name": "小学教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040108", "name": "特殊教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040109", "name": "华文教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040110", "name": "教育康复学", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040111", "name": "卫生教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040112", "name": "认知科学与技术", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040113", "name": "融合教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040201", "name": "体育教育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040202", "name": "运动训练", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040203", "name": "社会体育指导与管理", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040204", "name": "武术与民族传统体育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040205", "name": "运动人体科学", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040206", "name": "运动康复", "category": "教育学", "degree_type": "理学或教育学"},
    {"standard_code": "040207", "name": "休闲体育", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040208", "name": "体能训练", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040209", "name": "冰雪运动", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040210", "name": "电子竞技运动与管理", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040211", "name": "智能体育工程", "category": "教育学", "degree_type": "工学"},
    {"standard_code": "040212", "name": "体育旅游", "category": "教育学", "degree_type": "教育学"},
    {"standard_code": "040213", "name": "运动能力开发", "category": "教育学", "degree_type": "教育学"},

    # ==================== 05 文学 ====================
    {"standard_code": "050101", "name": "汉语言文学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050102", "name": "汉语言", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050103", "name": "汉语国际教育", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050104", "name": "中国少数民族语言文学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050105", "name": "古典文献学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050106", "name": "应用语言学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050107", "name": "秘书学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050108", "name": "中国语言与文化", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050109", "name": "手语翻译", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050110", "name": "数字人文", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050201", "name": "英语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050202", "name": "俄语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050203", "name": "德语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050204", "name": "法语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050205", "name": "西班牙语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050206", "name": "阿拉伯语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050207", "name": "日语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050208", "name": "波斯语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050209", "name": "朝鲜语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050210", "name": "菲律宾语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050211", "name": "梵语巴利语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050212", "name": "印度尼西亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050213", "name": "印地语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050214", "name": "柬埔寨语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050215", "name": "老挝语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050216", "name": "缅甸语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050217", "name": "马来语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050218", "name": "蒙古语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050219", "name": "僧伽罗语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050220", "name": "泰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050221", "name": "乌尔都语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050222", "name": "希伯来语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050223", "name": "越南语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050224", "name": "豪萨语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050225", "name": "斯瓦希里语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050226", "name": "阿尔巴尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050227", "name": "保加利亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050228", "name": "波兰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050229", "name": "捷克语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050230", "name": "斯洛伐克语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050231", "name": "罗马尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050232", "name": "葡萄牙语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050233", "name": "瑞典语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050234", "name": "塞尔维亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050235", "name": "土耳其语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050236", "name": "希腊语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050237", "name": "匈牙利语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050238", "name": "意大利语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050239", "name": "泰米尔语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050240", "name": "普什图语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050241", "name": "世界语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050242", "name": "孟加拉语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050243", "name": "尼泊尔语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050244", "name": "克罗地亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050245", "name": "荷兰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050246", "name": "芬兰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050247", "name": "乌克兰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050248", "name": "挪威语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050249", "name": "丹麦语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050250", "name": "冰岛语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050251", "name": "爱尔兰语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050252", "name": "拉脱维亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050253", "name": "立陶宛语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050254", "name": "斯洛文尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050255", "name": "爱沙尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050256", "name": "马耳他语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050257", "name": "哈萨克语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050258", "name": "乌兹别克语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050259", "name": "祖鲁语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050260", "name": "拉丁语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050261", "name": "翻译", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050262", "name": "商务英语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050263", "name": "阿姆哈拉语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050264", "name": "吉尔吉斯语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050265", "name": "索马里语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050266", "name": "土库曼语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050267", "name": "加泰罗尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050268", "name": "约鲁巴语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050269", "name": "亚美尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050270", "name": "马达加斯加语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050271", "name": "格鲁吉亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050272", "name": "阿塞拜疆语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050273", "name": "阿非利卡语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050274", "name": "马其顿语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050275", "name": "塔吉克语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050276", "name": "白俄罗斯语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050277", "name": "波斯尼亚语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050278", "name": "僧伽罗语（斯里兰卡）", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050279", "name": "毛利语", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050280", "name": "语言学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050301", "name": "新闻学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050302", "name": "广播电视学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050303", "name": "广告学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050304", "name": "传播学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050305", "name": "编辑出版学", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050306", "name": "网络与新媒体", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050307", "name": "数字出版", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050308", "name": "时尚传播", "category": "文学", "degree_type": "文学"},
    {"standard_code": "050309", "name": "国际新闻与传播", "category": "文学", "degree_type": "文学"},

    # ==================== 06 历史学 ====================
    {"standard_code": "060101", "name": "历史学", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060102", "name": "世界史", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060103", "name": "考古学", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060104", "name": "文物与博物馆学", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060105", "name": "文物保护技术", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060106", "name": "外国语言与外国历史", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060107", "name": "文化遗产", "category": "历史学", "degree_type": "历史学"},
    {"standard_code": "060108", "name": "古文字学", "category": "历史学", "degree_type": "历史学"},

    # ==================== 07 理学 ====================
    {"standard_code": "070101", "name": "数学与应用数学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070102", "name": "信息与计算科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070103", "name": "数理基础科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070104", "name": "数据计算及应用", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070201", "name": "物理学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070202", "name": "应用物理学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070203", "name": "核物理", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070204", "name": "声学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070205", "name": "系统科学与工程", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070206", "name": "量子信息科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070301", "name": "化学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070302", "name": "应用化学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070303", "name": "化学生物学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070304", "name": "分子科学与工程", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070305", "name": "能源化学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070306", "name": "化学测量学与技术", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070401", "name": "天文学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070501", "name": "地理科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070502", "name": "自然地理与资源环境", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070503", "name": "人文地理与城乡规划", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070504", "name": "地理信息科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070601", "name": "大气科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070602", "name": "应用气象学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070603", "name": "气象技术与工程", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070701", "name": "海洋科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070702", "name": "海洋技术", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070703", "name": "海洋资源与环境", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070704", "name": "军事海洋学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070801", "name": "地球物理学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070802", "name": "空间科学与技术", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070803", "name": "防灾减灾科学与工程", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070901", "name": "地质学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070902", "name": "地球化学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070903", "name": "古生物学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "070904", "name": "地球信息科学与技术", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071001", "name": "生物科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071002", "name": "生物技术", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071003", "name": "生物信息学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071004", "name": "生态学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071005", "name": "整合科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071006", "name": "神经科学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071101", "name": "心理学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071102", "name": "应用心理学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071201", "name": "统计学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071202", "name": "应用统计学", "category": "理学", "degree_type": "理学"},
    {"standard_code": "071203", "name": "数据科学", "category": "理学", "degree_type": "理学"},

    # ==================== 08 工学 ====================
    {"standard_code": "080101", "name": "理论与应用力学", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080102", "name": "工程力学", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080201", "name": "机械工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080202", "name": "机械设计制造及其自动化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080203", "name": "材料成型及控制工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080204", "name": "机械电子工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080205", "name": "工业设计", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080206", "name": "过程装备与控制工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080207", "name": "车辆工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080208", "name": "汽车服务工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080209", "name": "机械工艺技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080210", "name": "微机电系统工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080211", "name": "机电技术教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080212", "name": "汽车维修工程教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080213", "name": "智能制造工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080214", "name": "智能车辆工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080215", "name": "仿生科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080216", "name": "新能源汽车工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080217", "name": "增材制造工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080301", "name": "测控技术与仪器", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080302", "name": "精密仪器", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080303", "name": "智能感知工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080401", "name": "材料科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080402", "name": "材料物理", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "080403", "name": "材料化学", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "080404", "name": "冶金工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080405", "name": "金属材料工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080406", "name": "无机非金属材料工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080407", "name": "高分子材料与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080408", "name": "复合材料与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080409", "name": "粉体材料科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080410", "name": "宝石及材料工艺学", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080411", "name": "焊接技术与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080412", "name": "功能材料", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080413", "name": "纳米材料与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080414", "name": "新能源材料与器件", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080415", "name": "材料设计科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080416", "name": "复合材料成型工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080417", "name": "智能材料与结构", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080501", "name": "能源与动力工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080502", "name": "能源与环境系统工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080503", "name": "新能源科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080504", "name": "储能科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080505", "name": "能源服务工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080506", "name": "氢能科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080601", "name": "电气工程及其自动化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080602", "name": "智能电网信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080603", "name": "光源与照明", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080604", "name": "电气工程与智能控制", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080605", "name": "电机电器智能化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080606", "name": "电缆工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080607", "name": "能源互联网工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080701", "name": "电子信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080702", "name": "电子科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080703", "name": "通信工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080704", "name": "微电子科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080705", "name": "光电信息科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080706", "name": "信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080707", "name": "广播电视工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080708", "name": "水声工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080709", "name": "电子封装技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080710", "name": "集成电路设计与集成系统", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080711", "name": "医学信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080712", "name": "电磁场与无线技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080713", "name": "电波传播与天线", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080714", "name": "电子信息科学与技术", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "080715", "name": "电信工程及管理", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080716", "name": "应用电子技术教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080717", "name": "人工智能", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080718", "name": "海洋信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080719", "name": "柔性电子学", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080720", "name": "智能测控工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080801", "name": "自动化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080802", "name": "轨道交通信号与控制", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080803", "name": "机器人工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080804", "name": "邮政工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080805", "name": "核电技术与控制工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080806", "name": "智能装备与系统", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080807", "name": "工业智能", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080901", "name": "计算机科学与技术", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "080902", "name": "软件工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080903", "name": "网络工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080904", "name": "信息安全", "category": "工学", "degree_type": "管理学或理学或工学"},
    {"standard_code": "080905", "name": "物联网工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080906", "name": "数字媒体技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080907", "name": "智能科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080908", "name": "空间信息与数字技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080909", "name": "电子与计算机工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080910", "name": "数据科学与大数据技术", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "080911", "name": "网络空间安全", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080912", "name": "新媒体技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080913", "name": "电影制作", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080914", "name": "保密技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080915", "name": "服务科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080916", "name": "虚拟现实技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080917", "name": "区块链工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "080918", "name": "密码科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081001", "name": "土木工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081002", "name": "建筑环境与能源应用工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081003", "name": "给排水科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081004", "name": "建筑电气与智能化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081005", "name": "城市地下空间工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081006", "name": "道路桥梁与渡河工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081007", "name": "铁道工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081008", "name": "智能建造", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081009", "name": "土木、水利与海洋工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081010", "name": "土木、水利与交通工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081101", "name": "水利水电工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081102", "name": "水文与水资源工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081103", "name": "港口航道与海岸工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081104", "name": "水务工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081105", "name": "水利科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081106", "name": "智慧水利", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081201", "name": "测绘工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081202", "name": "遥感科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081203", "name": "导航工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081204", "name": "地理国情监测", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081205", "name": "地理空间信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081301", "name": "化学工程与工艺", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081302", "name": "制药工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081303", "name": "资源循环科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081304", "name": "能源化学工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081305", "name": "化学工程与工业生物工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081306", "name": "化工安全工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081307", "name": "涂料工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081308", "name": "精细化工", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081401", "name": "地质工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081402", "name": "勘查技术与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081403", "name": "资源勘查工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081404", "name": "地下水科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081405", "name": "旅游地学与规划工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081501", "name": "采矿工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081502", "name": "石油工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081503", "name": "矿物加工工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081504", "name": "油气储运工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081505", "name": "矿物资源工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081506", "name": "海洋油气工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081507", "name": "智能采矿工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081508", "name": "碳储科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081601", "name": "纺织工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081602", "name": "服装设计与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081603", "name": "非织造材料与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081604", "name": "服装设计与工艺教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081605", "name": "丝绸设计与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081701", "name": "轻化工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081702", "name": "包装工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081703", "name": "印刷工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081704", "name": "香料香精技术与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081705", "name": "化妆品技术与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081801", "name": "交通运输", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081802", "name": "交通工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081803", "name": "航海技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081804", "name": "轮机工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081805", "name": "飞行技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081806", "name": "交通设备与控制工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081807", "name": "救助与打捞工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081808", "name": "船舶电子电气工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081809", "name": "轨道交通电气与控制", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081810", "name": "邮轮工程与管理", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081811", "name": "智慧交通", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081812", "name": "智能运输工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081901", "name": "船舶与海洋工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081902", "name": "海洋工程与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081903", "name": "海洋资源开发技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081904", "name": "海洋机器人", "category": "工学", "degree_type": "工学"},
    {"standard_code": "081905", "name": "智慧海洋技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082001", "name": "航空航天工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082002", "name": "飞行器设计与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082003", "name": "飞行器制造工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082004", "name": "飞行器动力工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082005", "name": "飞行器环境与生命保障工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082006", "name": "飞行器质量与可靠性", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082007", "name": "飞行器适航技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082008", "name": "飞行器控制与信息工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082009", "name": "无人驾驶航空器系统工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082010", "name": "智能飞行器技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082101", "name": "武器系统与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082102", "name": "武器发射工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082103", "name": "探测制导与控制技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082104", "name": "弹药工程与爆炸技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082105", "name": "特种能源技术与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082106", "name": "装甲车辆工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082107", "name": "信息对抗技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082108", "name": "智能无人系统技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082201", "name": "核工程与核技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082202", "name": "辐射防护与核安全", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082203", "name": "工程物理", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082204", "name": "核化工与核燃料工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082301", "name": "农业工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082302", "name": "农业机械化及其自动化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082303", "name": "农业电气化", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082304", "name": "农业建筑环境与能源工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082305", "name": "农业水利工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082306", "name": "土地整治工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082307", "name": "农业智能装备工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082401", "name": "森林工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082402", "name": "木材科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082403", "name": "林产化工", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082404", "name": "家具设计与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082405", "name": "木结构建筑与材料", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082501", "name": "环境科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082502", "name": "环境工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082503", "name": "环境科学", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "082504", "name": "环境生态工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082505", "name": "环保设备工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082506", "name": "资源环境科学", "category": "工学", "degree_type": "理学或工学"},
    {"standard_code": "082507", "name": "水质科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082508", "name": "碳中科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082601", "name": "生物医学工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082602", "name": "假肢矫形工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082603", "name": "临床工程技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082604", "name": "康复工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082701", "name": "食品科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082702", "name": "食品质量与安全", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082703", "name": "粮食工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082704", "name": "乳品工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082705", "name": "酿酒工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082706", "name": "葡萄与葡萄酒工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082707", "name": "食品营养与检验教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082708", "name": "烹饪与营养教育", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082709", "name": "食品安全与检测", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082710", "name": "食品营养与健康", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082711", "name": "食用菌科学与工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082712", "name": "白酒酿造工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082801", "name": "建筑学", "category": "工学", "degree_type": "建筑学"},
    {"standard_code": "082802", "name": "城乡规划", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082803", "name": "风景园林", "category": "工学", "degree_type": "工学或艺术学"},
    {"standard_code": "082804", "name": "历史建筑保护工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082805", "name": "人居环境科学与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082806", "name": "城市设计", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082807", "name": "智慧建筑与建造", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082901", "name": "安全工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082902", "name": "应急技术与管理", "category": "工学", "degree_type": "工学"},
    {"standard_code": "082903", "name": "职业卫生工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083001", "name": "生物工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083002", "name": "生物制药", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083003", "name": "合成生物学", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083101", "name": "刑事科学技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083102", "name": "消防工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083103", "name": "交通管理工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083104", "name": "安全防范工程", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083105", "name": "公安视听技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083106", "name": "抢险救援指挥与技术", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083107", "name": "火灾勘查", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083108", "name": "网络安全与执法", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083109", "name": "核生化消防", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083201", "name": "食品科学与工程（中外合作）", "category": "工学", "degree_type": "工学"},
    {"standard_code": "083202", "name": "生物工程（中外合作）", "category": "工学", "degree_type": "工学"},

    # ==================== 09 农学 ====================
    {"standard_code": "090101", "name": "农学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090102", "name": "园艺", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090103", "name": "植物保护", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090104", "name": "植物科学与技术", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090105", "name": "种子科学与工程", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090106", "name": "设施农业科学与工程", "category": "农学", "degree_type": "工学或农学"},
    {"standard_code": "090107", "name": "茶学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090108", "name": "烟草", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090109", "name": "应用生物科学", "category": "农学", "degree_type": "理学或农学"},
    {"standard_code": "090110", "name": "农艺教育", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090111", "name": "园艺教育", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090112", "name": "智慧农业", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090113", "name": "菌物科学与工程", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090114", "name": "农药化肥", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090115", "name": "生物育种科学", "category": "农学", "degree_type": "理学"},
    {"standard_code": "090116", "name": "生物育种技术", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090117", "name": "土地科学与技术", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090201", "name": "农业资源与环境", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090202", "name": "野生动物与自然保护区管理", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090203", "name": "水土保持与荒漠化防治", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090204", "name": "生物质科学与工程", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090301", "name": "动物科学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090302", "name": "蚕学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090303", "name": "蜂学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090304", "name": "经济动物学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090305", "name": "马业科学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090306", "name": "饲料工程", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090307", "name": "智慧牧业科学与工程", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090401", "name": "动物医学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090402", "name": "动物药学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090403", "name": "动植物检疫", "category": "农学", "degree_type": "理学或农学"},
    {"standard_code": "090404", "name": "实验动物学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090405", "name": "中兽医学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090406", "name": "兽医公共卫生", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090501", "name": "林学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090502", "name": "园林", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090503", "name": "森林保护", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090504", "name": "经济林", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090505", "name": "智慧林业", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090601", "name": "水产养殖学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090602", "name": "海洋渔业科学与技术", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090603", "name": "水族科学与技术", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090604", "name": "水生动物医学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090701", "name": "草业科学", "category": "农学", "degree_type": "农学"},
    {"standard_code": "090702", "name": "草坪科学与工程", "category": "农学", "degree_type": "农学"},

    # ==================== 10 医学 ====================
    {"standard_code": "100101", "name": "基础医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100102", "name": "生物医学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100103", "name": "生物医学科学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100201", "name": "临床医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100202", "name": "麻醉学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100203", "name": "医学影像学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100204", "name": "眼视光医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100205", "name": "精神医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100206", "name": "放射医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100207", "name": "儿科学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100301", "name": "口腔医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100401", "name": "预防医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100402", "name": "食品卫生与营养学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100403", "name": "妇幼保健医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100404", "name": "卫生监督", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100405", "name": "全球健康学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100406", "name": "运动与公共健康", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100501", "name": "中医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100502", "name": "针灸推拿学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100503", "name": "藏医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100504", "name": "蒙医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100505", "name": "维医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100506", "name": "壮医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100507", "name": "哈医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100508", "name": "傣医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100509", "name": "回医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100510", "name": "中医康复学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100511", "name": "中医养生学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100512", "name": "中医儿科学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100513", "name": "中医骨伤科学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100601", "name": "中西医临床医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "100701", "name": "药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100702", "name": "药物制剂", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100703", "name": "临床药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100704", "name": "药事管理", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100705", "name": "药物分析", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100706", "name": "药物化学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100707", "name": "海洋药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100708", "name": "化妆品科学与技术", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100801", "name": "中药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100802", "name": "中药资源与开发", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100803", "name": "藏药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100804", "name": "蒙药学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100805", "name": "中药制药", "category": "医学", "degree_type": "工学"},
    {"standard_code": "100806", "name": "中草药栽培与鉴定", "category": "医学", "degree_type": "理学"},
    {"standard_code": "100901", "name": "法医学", "category": "医学", "degree_type": "医学"},
    {"standard_code": "101001", "name": "医学检验技术", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101002", "name": "医学实验技术", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101003", "name": "医学影像技术", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101004", "name": "眼视光学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101005", "name": "康复治疗学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101006", "name": "口腔医学技术", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101007", "name": "卫生检验与检疫", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101008", "name": "听力与言语康复学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101009", "name": "康复物理治疗", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101010", "name": "康复作业治疗", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101011", "name": "智能医学工程", "category": "医学", "degree_type": "工学"},
    {"standard_code": "101012", "name": "生物医药数据科学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101013", "name": "智能影像工程", "category": "医学", "degree_type": "工学"},
    {"standard_code": "101014", "name": "医工学", "category": "医学", "degree_type": "工学"},
    {"standard_code": "101101", "name": "护理学", "category": "医学", "degree_type": "理学"},
    {"standard_code": "101102", "name": "助产学", "category": "医学", "degree_type": "理学"},

    # ==================== 11 军事学 ====================
    {"standard_code": "110101", "name": "军事思想及军事历史", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110102", "name": "战略学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110103", "name": "战役学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110104", "name": "战术学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110105", "name": "军队指挥学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110106", "name": "军事管理学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110107", "name": "军队政治工作学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110108", "name": "军事后勤学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110109", "name": "军事装备学", "category": "军事学", "degree_type": "军事学"},
    {"standard_code": "110110", "name": "军事训练学", "category": "军事学", "degree_type": "军事学"},

    # ==================== 12 管理学 ====================
    {"standard_code": "120101", "name": "管理科学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120102", "name": "信息管理与信息系统", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120103", "name": "工程管理", "category": "管理学", "degree_type": "工学"},
    {"standard_code": "120104", "name": "房地产开发与管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120105", "name": "工程造价", "category": "管理学", "degree_type": "工学"},
    {"standard_code": "120106", "name": "保密管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120107", "name": "邮政管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120108", "name": "大数据管理与应用", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120109", "name": "计算金融", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120110", "name": "应急管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120201", "name": "工商管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120202", "name": "市场营销", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120203", "name": "会计学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120204", "name": "财务管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120205", "name": "国际商务", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120206", "name": "人力资源管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120207", "name": "审计学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120208", "name": "资产评估", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120209", "name": "物业管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120210", "name": "文化产业管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120211", "name": "劳动关系", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120212", "name": "体育经济与管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120213", "name": "财务会计教育", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120214", "name": "市场营销教育", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120215", "name": "零售业管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120216", "name": "创业管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120217", "name": "海关稽查", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120301", "name": "农林经济管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120302", "name": "农村区域发展", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120303", "name": "乡村治理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120401", "name": "公共事业管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120402", "name": "行政管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120403", "name": "劳动与社会保障", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120404", "name": "土地资源管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120405", "name": "城市管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120406", "name": "海关管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120407", "name": "交通管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120408", "name": "海事管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120409", "name": "公共关系学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120410", "name": "健康服务与管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120411", "name": "海警后勤管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120412", "name": "医疗产品管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120413", "name": "医疗保险", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120414", "name": "养老服务管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120415", "name": "家政学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120416", "name": "慈善管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120417", "name": "无障碍管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120501", "name": "图书馆学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120502", "name": "档案学", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120503", "name": "信息资源管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120601", "name": "物流管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120602", "name": "物流工程", "category": "管理学", "degree_type": "工学"},
    {"standard_code": "120603", "name": "采购管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120604", "name": "供应链管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120701", "name": "工业工程", "category": "管理学", "degree_type": "工学"},
    {"standard_code": "120702", "name": "标准化工程", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120703", "name": "质量管理工程", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120801", "name": "电子商务", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120802", "name": "电子商务及法律", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120803", "name": "跨境电子商务", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120901", "name": "旅游管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120902", "name": "酒店管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120903", "name": "会展经济与管理", "category": "管理学", "degree_type": "管理学"},
    {"standard_code": "120904", "name": "旅游管理与服务教育", "category": "管理学", "degree_type": "管理学"},

    # ==================== 13 艺术学 ====================
    {"standard_code": "130101", "name": "艺术史论", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130102", "name": "艺术管理", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130103", "name": "非物质文化遗产保护", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130201", "name": "音乐表演", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130202", "name": "音乐学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130203", "name": "作曲与作曲技术理论", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130204", "name": "舞蹈表演", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130205", "name": "舞蹈学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130206", "name": "舞蹈编导", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130207", "name": "舞蹈教育", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130208", "name": "航空服务艺术与管理", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130209", "name": "流行音乐", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130210", "name": "音乐治疗", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130211", "name": "流行舞蹈", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130212", "name": "音乐教育", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130301", "name": "表演", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130302", "name": "戏剧学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130303", "name": "电影学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130304", "name": "戏剧影视文学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130305", "name": "广播电视编导", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130306", "name": "戏剧影视导演", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130307", "name": "戏剧影视美术设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130308", "name": "录音艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130309", "name": "播音与主持艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130310", "name": "动画", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130311", "name": "影视摄影与制作", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130312", "name": "影视技术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130313", "name": "戏剧教育", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130314", "name": "曲艺", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130315", "name": "音乐剧", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130401", "name": "美术学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130402", "name": "绘画", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130403", "name": "雕塑", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130404", "name": "摄影", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130405", "name": "书法学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130406", "name": "中国画", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130407", "name": "实验艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130408", "name": "跨媒体艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130409", "name": "文物保护与修复", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130410", "name": "漫画", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130411", "name": "纤维艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130412", "name": "科技艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130413", "name": "美术教育", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130501", "name": "设计学", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130502", "name": "视觉传达设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130503", "name": "环境设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130504", "name": "产品设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130505", "name": "服装与服饰设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130506", "name": "公共艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130507", "name": "工艺美术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130508", "name": "数字媒体艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130509", "name": "艺术与科技", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130510", "name": "陶瓷艺术设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130511", "name": "新媒体艺术", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130512", "name": "包装设计", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130513", "name": "珠宝首饰设计与工艺", "category": "艺术学", "degree_type": "艺术学"},
    {"standard_code": "130514", "name": "视觉传达设计（中外合作）", "category": "艺术学", "degree_type": "艺术学"},

    # ==================== 高职（专科）专业 ====================
    # 职业教育专业目录 — 仅列代表性专业
    {"standard_code": "410101", "name": "种子生产与经营", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410102", "name": "作物生产与经营管理", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410103", "name": "现代农业技术", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410105", "name": "园艺技术", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410106", "name": "植物保护与检疫技术", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410202", "name": "林业技术", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410301", "name": "动物医学", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410302", "name": "畜牧兽医", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "410303", "name": "宠物医疗技术", "category": "农林牧渔", "degree_type": "无"},
    {"standard_code": "420101", "name": "国土资源调查与管理", "category": "资源环境与安全", "degree_type": "无"},
    {"standard_code": "420201", "name": "煤矿智能开采技术", "category": "资源环境与安全", "degree_type": "无"},
    {"standard_code": "420301", "name": "工程测量技术", "category": "资源环境与安全", "degree_type": "无"},
    {"standard_code": "420901", "name": "安全技术与管理", "category": "资源环境与安全", "degree_type": "无"},
    {"standard_code": "430101", "name": "发电厂及电力系统", "category": "能源动力与材料", "degree_type": "无"},
    {"standard_code": "430201", "name": "新能源材料应用技术", "category": "能源动力与材料", "degree_type": "无"},
    {"standard_code": "440101", "name": "建筑设计", "category": "土木建筑", "degree_type": "无"},
    {"standard_code": "440102", "name": "建筑装饰工程技术", "category": "土木建筑", "degree_type": "无"},
    {"standard_code": "440301", "name": "建筑工程技术", "category": "土木建筑", "degree_type": "无"},
    {"standard_code": "440401", "name": "工程造价", "category": "土木建筑", "degree_type": "无"},
    {"standard_code": "440501", "name": "建设工程管理", "category": "土木建筑", "degree_type": "无"},
    {"standard_code": "450101", "name": "水文与水资源技术", "category": "水利", "degree_type": "无"},
    {"standard_code": "450201", "name": "水利工程", "category": "水利", "degree_type": "无"},
    {"standard_code": "460101", "name": "机械设计与制造", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460102", "name": "数字化设计与制造技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460103", "name": "数控技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460104", "name": "机械制造及自动化", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460105", "name": "工业设计", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460106", "name": "工业工程技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460201", "name": "智能制造装备技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460301", "name": "机电一体化技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460303", "name": "智能控制技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460305", "name": "工业机器人技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460306", "name": "电气自动化技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460401", "name": "汽车制造与试验技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "460701", "name": "汽车检测与维修技术", "category": "装备制造", "degree_type": "无"},
    {"standard_code": "470101", "name": "应用化工技术", "category": "生物与化工", "degree_type": "无"},
    {"standard_code": "470102", "name": "石油化工技术", "category": "生物与化工", "degree_type": "无"},
    {"standard_code": "470201", "name": "药品生产技术", "category": "生物与化工", "degree_type": "无"},
    {"standard_code": "480101", "name": "食品智能加工技术", "category": "轻工纺织", "degree_type": "无"},
    {"standard_code": "480201", "name": "包装工程技术", "category": "轻工纺织", "degree_type": "无"},
    {"standard_code": "480202", "name": "印刷媒体技术", "category": "轻工纺织", "degree_type": "无"},
    {"standard_code": "480401", "name": "纺织工艺技术", "category": "轻工纺织", "degree_type": "无"},
    {"standard_code": "490101", "name": "食品质量与安全", "category": "食品药品与粮食", "degree_type": "无"},
    {"standard_code": "490201", "name": "药品经营与管理", "category": "食品药品与粮食", "degree_type": "无"},
    {"standard_code": "490202", "name": "药学", "category": "食品药品与粮食", "degree_type": "无"},
    {"standard_code": "490203", "name": "中药学", "category": "食品药品与粮食", "degree_type": "无"},
    {"standard_code": "500101", "name": "铁道工程技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500102", "name": "铁道机车运用与维护", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500103", "name": "铁道车辆技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500104", "name": "铁道供电技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500105", "name": "铁道通信与信息化技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500106", "name": "铁道信号自动控制", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500107", "name": "铁道交通运营管理", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500108", "name": "高速铁路客运服务", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500201", "name": "道路与桥梁工程技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500203", "name": "智能工程机械运用技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500301", "name": "航海技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500302", "name": "轮机工程技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500401", "name": "民航运输服务", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500402", "name": "空中乘务", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500403", "name": "民航安全技术管理", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500405", "name": "飞机机电设备维修", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500406", "name": "无人机应用技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500601", "name": "城市轨道交通工程技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500602", "name": "城市轨道车辆应用技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500603", "name": "城市轨道交通机电技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500604", "name": "城市轨道交通通信信号技术", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500605", "name": "城市轨道交通运营管理", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "500701", "name": "邮政快递运营管理", "category": "交通运输", "degree_type": "无"},
    {"standard_code": "510101", "name": "电子信息工程技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510102", "name": "物联网应用技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510103", "name": "应用电子技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510104", "name": "电子产品制造技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510105", "name": "电子产品检测技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510106", "name": "移动互联应用技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510107", "name": "汽车智能技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510108", "name": "智能产品开发与应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510109", "name": "智能光电技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510110", "name": "光电显示技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510201", "name": "计算机应用技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510202", "name": "计算机网络技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510203", "name": "软件技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510204", "name": "数字媒体技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510205", "name": "大数据技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510206", "name": "云计算技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510207", "name": "人工智能技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510208", "name": "虚拟现实技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510209", "name": "移动应用开发", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510210", "name": "工业软件开发技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510211", "name": "区块链技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510212", "name": "密码技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510213", "name": "信息安全技术应用", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510301", "name": "现代通信技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510302", "name": "通信系统运行管理", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "510307", "name": "智能互联网络技术", "category": "电子信息", "degree_type": "无"},
    {"standard_code": "520101", "name": "临床医学", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520102", "name": "口腔医学", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520201", "name": "护理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520202", "name": "助产", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520301", "name": "药学", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520302", "name": "中药学", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520303", "name": "中药材生产与加工", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520401", "name": "医学检验技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520402", "name": "医学影像技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520403", "name": "医学生物技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520404", "name": "口腔医学技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520405", "name": "康复治疗技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520406", "name": "卫生检验与检疫技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520407", "name": "眼视光技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520408", "name": "放射治疗技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520501", "name": "医学美容技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520601", "name": "康复辅助器具技术", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520701", "name": "公共卫生管理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520702", "name": "卫生信息管理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520801", "name": "健康管理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520802", "name": "婴幼儿托育服务与管理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520803", "name": "老年保健与管理", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520901", "name": "心理咨询", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "520902", "name": "医学文秘", "category": "医药卫生", "degree_type": "无"},
    {"standard_code": "530101", "name": "财税大数据应用", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530102", "name": "资产评估与管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530201", "name": "金融管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530202", "name": "金融科技应用", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530301", "name": "大数据与财务管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530302", "name": "大数据与会计", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530303", "name": "大数据与审计", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530304", "name": "会计信息管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530401", "name": "统计与大数据分析", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530501", "name": "国际经济与贸易", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530502", "name": "国际商务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530503", "name": "关务与外贸服务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530601", "name": "工商企业管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530602", "name": "连锁经营与管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530603", "name": "商务管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530604", "name": "中小企业创业与经营", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530605", "name": "市场营销", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530701", "name": "电子商务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530702", "name": "跨境电子商务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530703", "name": "移动商务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530704", "name": "网络营销与直播电商", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530705", "name": "农村电子商务", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530706", "name": "商务数据分析与应用", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530801", "name": "物流工程技术", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530802", "name": "现代物流管理", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "530803", "name": "供应链运营", "category": "财经商贸", "degree_type": "无"},
    {"standard_code": "540101", "name": "旅游管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540102", "name": "导游", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540103", "name": "旅行社经营与管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540106", "name": "酒店管理与数字化运营", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540107", "name": "民宿管理与运营", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540108", "name": "智慧景区开发与管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540109", "name": "会展策划与管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540110", "name": "休闲服务与管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540201", "name": "餐饮智能管理", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540202", "name": "烹饪工艺与营养", "category": "旅游", "degree_type": "无"},
    {"standard_code": "540203", "name": "中西面点工艺", "category": "旅游", "degree_type": "无"},
    {"standard_code": "550101", "name": "艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550102", "name": "视觉传达设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550103", "name": "数字媒体艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550104", "name": "产品艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550105", "name": "服装与服饰设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550106", "name": "环境艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550107", "name": "书画艺术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550108", "name": "公共艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550109", "name": "游戏艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550110", "name": "展示艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550111", "name": "美容美体艺术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550112", "name": "工艺美术品设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550113", "name": "广告艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550114", "name": "室内艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550115", "name": "家具艺术设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550116", "name": "动漫设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550117", "name": "人物形象设计", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550118", "name": "摄影与摄像艺术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550201", "name": "音乐表演", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550202", "name": "舞蹈表演", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550203", "name": "戏曲表演", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550204", "name": "表演艺术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550205", "name": "戏剧影视表演", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550206", "name": "歌舞表演", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550207", "name": "时尚表演与传播", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550208", "name": "现代流行音乐", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550209", "name": "作曲技术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550210", "name": "钢琴调律", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550211", "name": "舞蹈编导", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550301", "name": "民族表演艺术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550401", "name": "文化创意与策划", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550402", "name": "文化产业经营与管理", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550403", "name": "公共文化服务与管理", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550404", "name": "文物修复与保护", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550405", "name": "文物考古技术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550406", "name": "文物展示利用技术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550407", "name": "图书档案管理", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "550408", "name": "石窟寺保护技术", "category": "文化艺术", "degree_type": "无"},
    {"standard_code": "560101", "name": "新闻采编与制作", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560102", "name": "网络新闻与传播", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560103", "name": "出版策划与编辑", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560201", "name": "播音与主持", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560202", "name": "广播影视节目制作", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560203", "name": "数字广播电视技术", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560204", "name": "影视编导", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560205", "name": "新闻采编与制作(影视)", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560206", "name": "影视动画", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560207", "name": "影视多媒体技术", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560208", "name": "摄影摄像技术", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560209", "name": "融媒体技术与运营", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560210", "name": "网络直播与运营", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "560211", "name": "全媒体广告策划与营销", "category": "新闻传播", "degree_type": "无"},
    {"standard_code": "570101", "name": "早期教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570102", "name": "学前教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570103", "name": "小学教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570104", "name": "小学语文教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570105", "name": "小学数学教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570106", "name": "小学英语教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570107", "name": "小学科学教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570108", "name": "音乐教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570109", "name": "美术教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570110", "name": "体育教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570111", "name": "舞蹈教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570112", "name": "艺术教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570113", "name": "特殊教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570114", "name": "现代教育技术", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570115", "name": "心理健康教育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570201", "name": "商务英语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570202", "name": "应用英语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570203", "name": "旅游英语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570204", "name": "应用韩语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570205", "name": "商务日语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570206", "name": "应用日语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570207", "name": "旅游日语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570208", "name": "应用外语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570209", "name": "中文", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570210", "name": "应用俄语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570211", "name": "应用法语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570212", "name": "应用西班牙语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570213", "name": "应用德语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570214", "name": "应用泰语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570215", "name": "应用越南语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570216", "name": "应用阿拉伯语", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570301", "name": "社会体育", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570302", "name": "运动训练", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570303", "name": "运动防护", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570304", "name": "社会体育指导与管理", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570305", "name": "电子竞技运动与管理", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570306", "name": "体育保健与康复", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "570307", "name": "健身指导与管理", "category": "教育与体育", "degree_type": "无"},
    {"standard_code": "580101", "name": "法律事务", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580102", "name": "法律文秘", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580103", "name": "司法助理", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580104", "name": "检察事务", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580201", "name": "刑事执行", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580202", "name": "民事执行", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580203", "name": "行政执行", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580204", "name": "司法警务", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580205", "name": "社区矫正", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580301", "name": "刑事侦查技术", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580302", "name": "司法鉴定技术", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580303", "name": "安全防范技术", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580304", "name": "司法信息技术", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580305", "name": "司法信息安全", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580401", "name": "法律执行", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580501", "name": "刑事侦查", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580601", "name": "治安管理", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580602", "name": "交通管理", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "580603", "name": "警务指挥与战术", "category": "公安与司法", "degree_type": "无"},
    {"standard_code": "590101", "name": "社会工作", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590102", "name": "党务工作", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590103", "name": "青少年工作与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590104", "name": "社区管理与服务", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590105", "name": "公共关系", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590106", "name": "公益慈善事业管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590201", "name": "民政管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590202", "name": "人力资源管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590203", "name": "劳动与社会保障", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590204", "name": "网络舆情监测", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590205", "name": "公共事务管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590206", "name": "行政管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590207", "name": "质量管理与认证", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590208", "name": "知识产权管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590209", "name": "文化产业服务与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590210", "name": "标准化技术", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590301", "name": "现代家政服务与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590302", "name": "智慧健康养老服务与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590303", "name": "社区康复", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590304", "name": "婚庆服务与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590305", "name": "现代殡葬技术与管理", "category": "公共管理与服务", "degree_type": "无"},
    {"standard_code": "590401", "name": "城市管理与监察", "category": "公共管理与服务", "degree_type": "无"},
]


class MajorCollector(BaseCollector):
    """教育部专业目录采集器。

    数据来源：教育部《普通高等学校本科专业目录（2024年版）》
    和《职业教育专业目录》，内建完整数据约800+个专业。
    """

    name = "majors"

    def __init__(self, **kwargs):
        kwargs.setdefault("use_proxy", False)
        super().__init__(**kwargs)

    async def collect(self) -> int:
        if not self.db:
            logger.error("No database backend set, cannot save majors")
            return 0

        logger.info(
            "Starting major collection (built-in data: %d majors)",
            len(MAJORS_DATA),
        )
        count = 0

        for major in MAJORS_DATA:
            try:
                await self._save_major(major)
                count += 1
            except Exception as e:
                logger.error(
                    "Failed to save major %s: %s", major["name"], e
                )

        logger.info("Major collection done: %d majors saved", count)
        return count

    async def _save_major(self, major: dict):
        """写入一条专业记录。"""
        # 检查是否已存在（按名称和门类去重，避免标准代码冲突）
        existing = await self.db.fetch_one(
            "SELECT id FROM majors WHERE name = ? AND category = ?",
            (major["name"], major.get("category", "")),
        )
        if existing:
            return

        await self.db.execute(
            """INSERT INTO majors (standard_code, name, category, degree_type)
               VALUES (?, ?, ?, ?)""",
            (
                major.get("standard_code", ""),
                major["name"],
                major.get("category", ""),
                major.get("degree_type", ""),
            ),
        )
